Repository redacademy/monkiri-spring-2019, pull requests merged in 2019-06, with the labels that each got.

#11 Nz install libraries
  README.md
  android/app/build.gradle
  android/app/src/main/assets/fonts/AntDesign.ttf
  android/app/src/main/assets/fonts/Entypo.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/FontAwesome.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/Foundation.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/MaterialIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  android/app/src/main/assets/fonts/Zocial.ttf
  android/app/src/main/java/com/monkirispring2019/MainApplication.java
  android/settings.gradle
  ios/monkiriSpring2019.xcodeproj/project.pbxproj
  ios/monkiriSpring2019/Info.plist
  package.json
  yarn.lock
Labels: good first issue

#14 Jf feature navigator
  App.js
  js/navigation/Config.js
  js/navigation/NavigationLayout.js
  js/navigation/RootStackNavigator.js
  js/navigation/index.js
  js/screens/Lessons/LessonsContainer.js
  js/screens/Lessons/index.js
  js/screens/Lessons/styles.js
  js/screens/Partners/PartnersContainer.js
  js/screens/Partners/index.js
  js/screens/Partners/styles.js
  js/screens/Profile/ProfileContainer.js
  js/screens/Profile/index.js
  js/screens/Profile/styles.js
  js/screens/Quests/QuestContainer.js
  js/screens/Quests/index.js
  js/screens/Quests/styles.js
Labels: enhancement

#35 Install apollo-boost react-apollo and graphql
  client/package.json
  client/yarn.lock
Labels: enhancement

#36 Install graphql-tag
  client/package.json
  client/yarn.lock
Labels: enhancement

#45 Add apollo provider
  client/App.js
  client/js/config/api.js
Labels: enhancement

#44 Add theme object to use for global styling
  client/js/config/styles.js
Labels: documentation, enhancement

#43 Install react-native-swiper
  client/package.json
  client/yarn.lock
Labels: enhancement

#47 Add global fonts
  client/android/app/src/main/assets/fonts/Quicksand-Bold.ttf
  client/android/app/src/main/assets/fonts/Quicksand-Light.ttf
  client/android/app/src/main/assets/fonts/Quicksand-Medium.ttf
  client/android/app/src/main/assets/fonts/Quicksand-Regular.ttf
  client/ios/monkiriSpring2019/Info.plist
  client/js/assets/fonts/Quicksand-Bold.ttf
  client/js/assets/fonts/Quicksand-Light.ttf
  client/js/assets/fonts/Quicksand-Medium.ttf
  client/js/assets/fonts/Quicksand-Regular.ttf
  client/package.json
Labels: enhancement

#52 Install react final form
  client/package.json
  client/yarn.lock
Labels: enhancement

#55 Ek feature global fonts
  client/js/config/styles.js
Labels: bug

#53 Nz feature reusable components
  client/js/components/TopicItem/TopicItem.js
  client/js/components/TopicItem/index.js
  client/js/components/TopicItem/styles.js
  client/js/components/TopicList/TopicList.js
  client/js/components/TopicList/index.js
  client/js/components/TopicList/styles.js
Labels: enhancement

#58 Ek feature signin screen
  client/js/assets/images/facebook.png
  client/js/assets/images/google.png
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/helpers/validate.js
  client/js/screens/SignIn/styles.js
Labels: enhancement

#32 Jf feature partners
  client/js/helpers/partners.js
  client/js/screens/Partners/PartnersContainer.js
  client/js/screens/Partners/styles.js
  client/js/screens/Profile/Profile.js
Labels: enhancement

#60 Jf feature onboarding
  client/js/assets/images/onBoarding/logo.png
  client/js/assets/images/onBoarding/onboarding01.png
  client/js/assets/images/onBoarding/onboarding02.png
  client/js/components/OnboardingAuth/OnboardingAuth.js
  client/js/components/OnboardingAuth/index.js
  client/js/components/OnboardingAuth/styles.js
  client/js/components/OnboardingIntro/OnboardingIntro.js
  client/js/components/OnboardingIntro/index.js
  client/js/components/OnboardingIntro/styles.js
  client/js/helpers/onboarding.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Onboarding/index.js
  client/js/screens/Onboarding/styles.js
Labels: enhancement

#61 Nz feature survey lessons screen
  client/js/components/TopicItem/styles.js
  client/js/components/TopicList/TopicList.js
  client/js/components/TopicList/styles.js
  client/js/helpers/topics.js
  client/js/screens/Lessons/SurveyLessons/SurveyLessons.js
  client/js/screens/Lessons/SurveyLessons/SurveyLessonsContainer.js
  client/js/screens/Lessons/SurveyLessons/index.js
  client/js/screens/Lessons/SurveyLessons/styles.js
Labels: enhancement

#70 Nz project dependecies
  client/package.json
  client/yarn.lock
Labels: enhancement

#37 St feature survey screen
  client/js/assets/images/Illustrations/Sprout@2xcopy.png
  client/js/assets/images/Illustrations/sprout.png
  client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
  client/js/screens/Lessons/SurveyDifficulty/index.js
  client/js/screens/Lessons/SurveyDifficulty/styles.js
Labels: enhancement

#72 Nz feature add global fonts
  client/ios/monkiriSpring2019.xcodeproj/project.pbxproj
Labels: bug

#78 Nz feature lesson popup
  client/js/components/LessonPopUp/LessonPopUp.js
  client/js/components/LessonPopUp/index.js
  client/js/components/LessonPopUp/styles.js
  client/js/components/TopicList/TopicList.js
  client/js/screens/Lessons/SurveyLessons/SurveyLessons.js
Labels: enhancement

#75 Jf feature progressinfo
  client/js/assets/images/Illustrations/circle.png
  client/js/assets/images/Illustrations/circleFalse.png
  client/js/assets/images/Illustrations/progressInfo.png
  client/js/assets/images/processGrow/grow0.png
  client/js/assets/images/processGrow/grow1.png
  client/js/assets/images/processGrow/grow2.png
  client/js/assets/images/processGrow/grow3.png
  client/js/components/ImageLoader/ImageLoader.js
  client/js/components/ImageLoader/index.js
  client/js/helpers/lessons.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/ProgressInfo/ProgressInfo.js
  client/js/screens/ProgressInfo/ProgressInfoContainer.js
  client/js/screens/ProgressInfo/index.js
  client/js/screens/ProgressInfo/styles.js
Labels: enhancement

#80 Add stage popup component
  client/js/components/StagePopUp/StagePopUp.js
  client/js/components/StagePopUp/index.js
  client/js/components/StagePopUp/styles.js
Labels: enhancement

#83 Change default image
  server/types.graphql
Labels: bug

#62 St feature lesson screen
  client/js/assets/images/Buttons/add.png
  client/js/assets/images/Buttons/play_button.png
  client/js/assets/images/IconsWhite/budgeting.png
  client/js/assets/images/IconsWhite/business.png
  client/js/assets/images/IconsWhite/debt.png
  client/js/assets/images/IconsWhite/insurance.png
  client/js/assets/images/IconsWhite/internationmoney.png
  client/js/assets/images/IconsWhite/investment.png
  client/js/assets/images/IconsWhite/mobilewallet.png
  client/js/assets/images/IconsWhite/saving.png
  client/js/assets/images/IconsWhite/taxes.png
  client/js/assets/images/mobileWallet/sproutpng.png
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/Lessons/styles.js
Labels: enhancement

#86 Nz feature project dependencies
  client/android/app/build.gradle
  client/android/app/src/main/java/com/monkirispring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/monkiriSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: enhancement

#81 Ek feature profile screen
  client/js/assets/images/profile-background.png
  client/js/assets/images/trophies-banner.png
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/styles.js
Labels: enhancement

#91 Jf feature calculator
  client/js/assets/images/dollar.png
  client/js/assets/images/percentage.png
  client/js/components/Calculator/Calculator.js
  client/js/components/Calculator/index.js
  client/js/components/Calculator/styles.js
  client/js/screens/Quests/QuestsContainer.js
Labels: enhancement

#92 Jf feature partners data
  client/js/assets/images/insurance.png
  client/js/assets/images/internationmoney.png
  client/js/assets/images/investment.png
  client/js/assets/images/mobilewallet.png
  client/js/assets/images/saving.png
  client/js/components/PartnersCardExpand/PartnersCardExpand.js
  client/js/helpers/partners.js
Labels: enhancement

#94 Remove the calculate button
  client/js/components/Calculator/Calculator.js
  client/js/components/Calculator/styles.js
Labels: enhancement

#95 Navigate to survey screens after singup
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
  client/js/screens/Lessons/SurveyDifficulty/index.js
  client/js/screens/Lessons/SurveyLessons/SurveyLessonsContainer.js
  client/js/screens/Lessons/SurveyLessons/index.js
  client/js/screens/SignUp/SignUp.js
  client/js/screens/SurveyDifficulty/SurveyDifficulty.js
  client/js/screens/SurveyDifficulty/SurveyDifficultyContainer.js
  client/js/screens/SurveyDifficulty/index.js
  client/js/screens/SurveyDifficulty/styles.js
  client/js/screens/SurveyLessons/SurveyLessons.js
  client/js/screens/SurveyLessons/SurveyLessonsContainer.js
  client/js/screens/SurveyLessons/index.js
  client/js/screens/SurveyLessons/styles.js
Labels: enhancement

#88 Nz feature stage two
  client/js/assets/images/mobileWallet/mobileWalletStage2.png
  client/js/components/StageTwo/StageTwo.js
  client/js/components/StageTwo/index.js
  client/js/components/StageTwo/styles.js
  client/js/helpers/topics.js
Labels: enhancement

#96 Nz feature stage complete
  client/js/assets/images/Illustrations/Completion_badge.png
  client/js/assets/images/Illustrations/Yellow_leaf.png
  client/js/components/StageComplete/StageComplete.js
  client/js/components/StageComplete/index.js
  client/js/components/StageComplete/styles.js
Labels: enhancement

#97 Nz feature gif popup
  client/js/assets/images/plantGifs/Seed_animation.gif
  client/js/components/GifPopUp/GifPopUp.js
  client/js/components/GifPopUp/index.js
  client/js/components/GifPopUp/styles.js
Labels: enhancement

#101 Remove header from auth and survey stacks
  client/js/navigation/RootStackNavigator.js
Labels: enhancement

#103 Nz feature project dependencies
  client/android/app/build.gradle
  client/android/app/src/main/java/com/monkirispring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/monkiriSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: enhancement

#104 Nz feature profile picture gravatar
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#102 Improvement for keyboard avoiding view
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignIn/styles.js
  client/js/screens/SignUp/SignUp.js
  client/js/screens/SignUp/styles.js
Labels: enhancement

#105 Improve profile screen styling
  client/js/assets/images/trophies-banner-left.png
  client/js/assets/images/trophies-banner-right.png
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/styles.js
Labels: enhancement

#106 St feature lesson library screen
  client/js/components/TopicItem/styles.js
  client/js/screens/Lessons/LessonLibrary.js
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/Lessons/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#107 Ek feature form error handling
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignUp/SignUp.js
Labels: enhancement

#110 Jf feature splash
  client/App.js
  client/ios/monkiriSpring2019.xcodeproj/project.pbxproj
  client/ios/monkiriSpring2019/AppDelegate.m
  client/ios/monkiriSpring2019/Base.lproj/LaunchScreen.xib
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  client/ios/monkiriSpring2019/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  client/ios/monkiriSpring2019/Images.xcassets/Contents.json
  client/ios/monkiriSpring2019/Images.xcassets/Image.imageset/Contents.json
  client/ios/monkiriSpring2019/Images.xcassets/Image.imageset/Logo - full.png
  client/ios/monkiriSpring2019/Images.xcassets/Image.imageset/Logo - full@2x.png
  client/ios/monkiriSpring2019/Images.xcassets/Image.imageset/Logo - full@3x.png
  client/js/components/Calculator/Calculator.js
Labels: enhancement

#111 Ek feature quests screen
  client/js/screens/Quests/Quests.js
  client/js/screens/Quests/QuestsContainer.js
  client/js/screens/Quests/styles.js
Labels: enhancement

#112 St feature lesson library screen
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/Lessons/styles.js
Labels: enhancement

#113 Ek feature lessons functionality
  client/App.js
  client/js/components/LessonPopUp/LessonPopUp.js
  client/js/components/TopicList/TopicList.js
  client/js/components/TopicList/styles.js
  client/js/context/LessonsContext.js
  client/js/context/index.js
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/SignUp/SignUp.js
Labels: enhancement

#114 Polished StageOne component
  client/js/components/StageOne/styles.js
Labels: enhancement

#117 ek feature library selected topics
  client/js/components/TopicItem/TopicItem.js
  client/js/components/TopicList/TopicList.js
Labels: enhancement

#116 Jf feature connectprogress
  client/js/components/Calculator/Calculator.js
  client/js/components/Calculator/styles.js
  client/js/components/GifPopUp/GifPopUp.js
  client/js/components/StageComplete/StageComplete.js
  client/js/components/StageOne/StageOne.js
  client/js/components/StageTwo/StageTwo.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/ProgressInfo/ProgressInfo.js
  client/js/screens/ProgressInfo/ProgressInfoContainer.js
Labels: enhancement

#118 Fix animation for the progress screen
  client/js/components/Calculator/Calculator.js
  client/js/components/StageOne/StageOne.js
  client/js/screens/ProgressInfo/ProgressInfo.js
Labels: enhancement

#119 Use context for xp
  client/js/context/LessonsContext.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/styles.js
  client/js/screens/ProgressInfo/ProgressInfo.js
Labels: enhancement

#120 Jf feature profile progressbar
  client/js/screens/ProgressInfo/ProgressInfo.js
Labels: enhancement

#121 ek bug cleanup code
  client/App.js
  client/index.js
  client/js/components/Calculator/Calculator.js
  client/js/components/Calculator/styles.js
  client/js/components/GifPopUp/GifPopUp.js
  client/js/components/LessonPopUp/styles.js
  client/js/components/OnboardingIntro/styles.js
  client/js/components/StageComplete/StageComplete.js
  client/js/components/StageOne/StageOne.js
  client/js/components/StagePopUp/StagePopUp.js
  client/js/components/StagePopUp/styles.js
  client/js/components/StageTwo/styles.js
  client/js/components/TopicList/styles.js
  client/js/navigation/Config.js
  client/js/screens/AuthLoading/AuthLoading.js
  client/js/screens/Quests/styles.js
  client/js/screens/SurveyLessons/styles.js
Labels: bug

#124 Nz feature stage one progressbar
  client/js/components/StageOne/StageOne.js
Labels: bug

#125 Add lessons completed context
  client/js/components/StageComplete/StageComplete.js
  client/js/context/LessonsContext.js
  client/js/screens/Profile/Profile.js
Labels: enhancement

#126 Change navigation back color to white
  client/js/navigation/Config.js
Labels: enhancement

#127 Add progress to context
  client/js/context/LessonsContext.js
  client/js/screens/Lessons/LessonLibrary.js
  client/js/screens/Lessons/LessonsContainer.js
  client/js/screens/ProgressInfo/ProgressInfo.js
Labels: enhancement

#123 Jf feature proptypes
  client/js/components/Calculator/Calculator.js
  client/js/components/GifPopUp/GifPopUp.js
  client/js/components/OnboardingAuth/OnboardingAuth.js
  client/js/components/OnboardingIntro/OnboardingIntro.js
  client/js/components/PartnersCard/PartnersCard.js
  client/js/components/PartnersCardExpand/PartnersCardExpand.js
  client/js/components/StageComplete/StageComplete.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Partners/Partners.js
  client/js/screens/ProgressInfo/ProgressInfo.js
Labels: enhancement
